metric_catalog_data <- tibble::tribble(
  ~metric, ~label, ~process_group, ~description, ~units, ~source_function,
  ~requires_optional_dependency, ~scale_sensitive, ~interpretation_notes,
  "bathy", "Bathymetry", "base_bathymetry",
  "Input bathymetric or elevation surface.", "input units", "as_bathy",
  FALSE, TRUE, "Interpretation follows the user-supplied vertical convention.",
  "slope_deg", "Slope", "slope_gradient",
  "Local slope gradient derived from the raster surface.", "degrees",
  "derive_slope", FALSE, TRUE,
  "Use projected coordinates for interpretable distance-based slopes.",
  "slope_rad", "Slope", "slope_gradient",
  "Local slope gradient derived from the raster surface.", "radians",
  "derive_slope", FALSE, TRUE,
  "Use projected coordinates for interpretable distance-based slopes.",
  "aspect_deg", "Aspect", "orientation",
  "Local downslope-facing orientation.", "degrees", "derive_aspect",
  FALSE, TRUE, "Circular metric; summarize with sine and cosine components.",
  "aspect_rad", "Aspect", "orientation",
  "Local downslope-facing orientation.", "radians", "derive_aspect",
  FALSE, TRUE, "Circular metric; summarize with sine and cosine components.",
  "northness", "Northness", "orientation",
  "Cosine transform of aspect.", "unitless", "derive_northness",
  FALSE, TRUE, "Positive values face north under the aspect convention.",
  "eastness", "Eastness", "orientation",
  "Sine transform of aspect.", "unitless", "derive_eastness",
  FALSE, TRUE, "Positive values face east under the aspect convention.",
  "hillshade", "Hillshade", "surface_structure",
  "Illumination model for visualizing terrain form.", "relative intensity",
  "derive_hillshade", FALSE, TRUE,
  "A visualization aid, not a physical measurement.",
  "roughness", "Roughness", "seafloor_rugosity",
  "Local range-based roughness from neighboring cells.", "input units",
  "derive_roughness", FALSE, TRUE,
  "Strongly affected by resolution and neighborhood definition.",
  "tri", "Terrain Ruggedness Index", "seafloor_rugosity",
  "Local terrain ruggedness index.", "input units", "derive_tri",
  FALSE, TRUE, "Compare only across compatible resolutions and extents.",
  "tpi", "Topographic Position Index", "seafloor_position",
  "Cell position relative to neighboring elevations.", "input units",
  "derive_tpi", FALSE, TRUE,
  "Sign interpretation depends on vertical sign convention.",
  "bpi_3x3", "Fine BPI", "seafloor_position",
  "Fine-scale bathymetric position index.", "input units", "derive_bpi",
  FALSE, TRUE, "Positive values mean higher-than-neighborhood stored values.",
  "bpi_11x11", "Broad BPI", "seafloor_position",
  "Broad-scale bathymetric position index.", "input units", "derive_bpi",
  FALSE, TRUE, "Positive values mean higher-than-neighborhood stored values.",
  "curvature", "Curvature", "curvature",
  "Laplacian-style local curvature proxy.", "input units per cell",
  "derive_curvature", FALSE, TRUE,
  "A lightweight curvature proxy; interpret with scale and CRS context.",
  "surface_area_ratio", "Surface Area Ratio", "surface_structure",
  "Approximate local surface area ratio derived from slope.", "unitless",
  "derive_surface_area_ratio", FALSE, TRUE,
  "Increases as slope steepens; sensitive to vertical and horizontal units.",
  "rugosity_vrm_3x3", "Vector Ruggedness", "seafloor_rugosity",
  "Vector ruggedness measure over a local window.", "unitless",
  "derive_rugosity", FALSE, TRUE,
  "Values approach 0 on planar surfaces and increase with orientation variation."
)

save(metric_catalog_data, file = "data/metric_catalog.rda", compress = "xz")
