metric_catalog_data <- tibble::tribble(
  ~metric, ~label, ~process_group, ~description, ~units, ~source_function,
  ~requires_optional_dependency, ~scale_sensitive, ~interpretation_notes,

  "bathy", "Bathymetry", "base_bathymetry",
  "Input bathymetric or elevation surface.", "input units", "as_bathy",
  FALSE, TRUE, "Interpretation follows the user-supplied vertical convention.",
  "hillshade", "Hillshade", "base_bathymetry",
  "Shaded-relief visualization of the bathymetric or elevation surface.", "relative intensity",
  "derive_hillshade", FALSE, TRUE,
  "A visualization aid for terrain form; not a physical measurement.",

  "aspect_deg", "Aspect", "seafloor_aspect",
  "Local downslope-facing orientation.", "degrees", "derive_aspect",
  FALSE, TRUE, "Circular metric; summarize with sine and cosine components.",
  "aspect_rad", "Aspect", "seafloor_aspect",
  "Local downslope-facing orientation.", "radians", "derive_aspect",
  FALSE, TRUE, "Circular metric; summarize with sine and cosine components.",
  "northness", "Northness", "seafloor_aspect",
  "Cosine transform of aspect describing north-south orientation.", "unitless",
  "derive_northness", FALSE, TRUE,
  "Positive values face north under the aspect convention.",
  "eastness", "Eastness", "seafloor_aspect",
  "Sine transform of aspect describing east-west orientation.", "unitless",
  "derive_eastness", FALSE, TRUE,
  "Positive values face east under the aspect convention.",
  "aspect_cos", "Northness", "seafloor_aspect",
  "Project-derived aspect cosine layer equivalent to northness.", "unitless",
  "external", TRUE, TRUE,
  "Accepted as an external layer name for compatibility with manuscript workflows.",
  "aspect_sin", "Eastness", "seafloor_aspect",
  "Project-derived aspect sine layer equivalent to eastness.", "unitless",
  "external", TRUE, TRUE,
  "Accepted as an external layer name for compatibility with manuscript workflows.",

  "slope_deg", "Slope", "slope_gradient",
  "Local steepness of the seabed at each cell.", "degrees",
  "derive_slope", FALSE, TRUE,
  "Use projected coordinates for interpretable distance-based slopes.",
  "slope_rad", "Slope", "slope_gradient",
  "Local steepness of the seabed at each cell.", "radians",
  "derive_slope", FALSE, TRUE,
  "Use projected coordinates for interpretable distance-based slopes.",
  "average_flowpath_slope_wbt", "Average Pathway Slope", "slope_gradient",
  "Average gradient of modeled upslope pathways draining through each cell.", "degrees",
  "external", TRUE, TRUE,
  "Terrain-routing proxy from an external workflow; not derived by blueterra.",

  "tpi", "Topographic Position Index", "seafloor_position",
  "Cell position relative to neighboring elevations.", "input units",
  "derive_tpi", FALSE, TRUE,
  "Sign interpretation depends on vertical sign convention.",
  "bpi_3x3", "Fine-scale BPI", "seafloor_position",
  "Fine-scale bathymetric position index.", "input units", "derive_bpi",
  FALSE, TRUE, "Positive values mean higher-than-neighborhood stored values.",
  "bpi_11x11", "Broad-scale BPI", "seafloor_position",
  "Broad-scale bathymetric position index.", "input units", "derive_bpi",
  FALSE, TRUE, "Positive values mean higher-than-neighborhood stored values.",
  "bpi_fine", "Fine-scale BPI", "seafloor_position",
  "Project-derived fine-scale bathymetric position index.", "input units",
  "external", TRUE, TRUE,
  "Accepted as an external layer name for compatibility with manuscript workflows.",
  "bpi_broad", "Broad-scale BPI", "seafloor_position",
  "Project-derived broad-scale bathymetric position index.", "input units",
  "external", TRUE, TRUE,
  "Accepted as an external layer name for compatibility with manuscript workflows.",
  "relative_topographic_position_wbt", "Relative Topographic Position", "seafloor_position",
  "Relative high, low, or intermediate position compared with nearby terrain.", "index",
  "external", TRUE, TRUE,
  "Terrain-position metric from an external workflow; not derived by blueterra.",
  "deviation_from_mean_elevation_wbt", "Deviation from Mean Elevation", "seafloor_position",
  "Difference between local depth and the average depth of the surrounding neighborhood.", "input units",
  "external", TRUE, TRUE,
  "External terrain-position layer; interpretation follows the stored vertical convention.",
  "difference_from_mean_elevation_wbt", "Difference from Mean Elevation", "seafloor_position",
  "Difference between a cell's depth and the mean depth around it.", "input units",
  "external", TRUE, TRUE,
  "External terrain-position layer; interpretation follows the stored vertical convention.",
  "elevation_relative_to_minmax_wbt", "Elevation Relative to Local Min and Max", "seafloor_position",
  "Scaled position within the local relief range.", "index",
  "external", TRUE, TRUE,
  "External terrain-position layer; interpretation follows the stored vertical convention.",

  "roughness", "Roughness", "seafloor_rugosity",
  "Difference between the maximum and minimum values in terra's local neighborhood.", "input units",
  "derive_roughness", FALSE, TRUE,
  "Strongly affected by resolution and neighborhood definition.",
  "tri", "Terrain Ruggedness Index", "seafloor_rugosity",
  "terra terrain ruggedness index calculated from local elevation differences.", "input units", "derive_tri",
  FALSE, TRUE, "Compare only across compatible resolutions and extents.",
  "rugosity_vrm_3x3", "Vector Ruggedness Measure", "seafloor_rugosity",
  "One minus the magnitude of the mean local slope-aspect normal vector.", "unitless",
  "derive_rugosity", FALSE, TRUE,
  "Values approach 0 on planar surfaces and increase with orientation variation.",
  "vrm", "Vector Ruggedness Measure", "seafloor_rugosity",
  "Project-derived vector ruggedness measure.", "unitless",
  "external", TRUE, TRUE,
  "Accepted as an external layer name for compatibility with manuscript workflows.",
  "ruggedness_index_wbt", "Ruggedness Index", "seafloor_rugosity",
  "External ruggedness metric summarizing local terrain irregularity.", "index",
  "external", TRUE, TRUE,
  "External ruggedness layer; compare only across compatible resolutions.",
  "surface_area_ratio", "Surface Area Ratio", "seafloor_rugosity",
  "Slope-secant approximation, 1 / cos(local slope), of surface-to-planar area ratio.", "unitless",
  "derive_surface_area_ratio", FALSE, TRUE,
  "Approximation, not a triangulated or directly measured benthic surface area.",
  "surface_area_ratio_wbt", "Surface Area Ratio", "seafloor_rugosity",
  "External surface-area ratio layer.", "unitless",
  "external", TRUE, TRUE,
  "Surface-area style metric retained with seafloor rugosity in the manuscript process grouping.",

  "curvature", "Four-neighbor Laplacian-style index", "curvature",
  "Sum of the four orthogonal neighbours minus four times the focal value.", "input units",
  "derive_curvature", FALSE, TRUE,
  "Unscaled by cell dimensions; not plan, profile, mean, or Gaussian curvature and strongly resolution-dependent.",
  "profile_curvature_wbt", "Profile Curvature", "curvature",
  "Curvature measured in the downslope direction.", "index",
  "external", TRUE, TRUE,
  "External curvature layer; not derived by blueterra.",
  "plan_curvature_wbt", "Plan Curvature", "curvature",
  "Curvature measured across the slope, perpendicular to downslope direction.", "index",
  "external", TRUE, TRUE,
  "External curvature layer; not derived by blueterra.",
  "tangential_curvature_wbt", "Tangential Curvature", "curvature",
  "Curvature related to lateral convergence or divergence across the slope.", "index",
  "external", TRUE, TRUE,
  "External curvature layer; not derived by blueterra.",
  "mean_curvature_wbt", "Mean Curvature", "curvature",
  "Average of the principal curvatures.", "index",
  "external", TRUE, TRUE,
  "External curvature layer; not derived by blueterra.",
  "gaussian_curvature_wbt", "Gaussian Curvature", "curvature",
  "Curvature metric based on the product of principal curvatures.", "index",
  "external", TRUE, TRUE,
  "External curvature layer; not derived by blueterra.",
  "minimal_curvature_wbt", "Minimal Curvature", "curvature",
  "Minimum principal curvature of the surface.", "index",
  "external", TRUE, TRUE,
  "External curvature layer; not derived by blueterra.",
  "maximal_curvature_wbt", "Maximal Curvature", "curvature",
  "Maximum principal curvature of the surface.", "index",
  "external", TRUE, TRUE,
  "External curvature layer; not derived by blueterra.",
  "total_curvature_wbt", "Total Curvature", "curvature",
  "Overall magnitude of local surface bending.", "index",
  "external", TRUE, TRUE,
  "External curvature layer; not derived by blueterra.",

  "flowacc", "Convergence Index", "accumulation_potential",
  "Terrain-derived index representing cells routed toward a location.", "index",
  "external", TRUE, TRUE,
  "Terrain-routing proxy for convergence or accumulation potential; not measured flow.",
  "d8_flow_accumulation_wbt", "D8 Convergence", "accumulation_potential",
  "Convergence estimated using a single downslope direction from each cell.", "index",
  "external", TRUE, TRUE,
  "Terrain-routing proxy for accumulation potential; not measured flow.",
  "dinf_flow_accumulation_wbt", "D-infinity Convergence", "accumulation_potential",
  "Convergence estimated using a continuous flow-direction method.", "index",
  "external", TRUE, TRUE,
  "Terrain-routing proxy for accumulation potential; not measured flow.",
  "fd8_flow_accumulation_wbt", "FD8 Convergence", "accumulation_potential",
  "Convergence estimated using a dispersed multi-direction routing method.", "index",
  "external", TRUE, TRUE,
  "Terrain-routing proxy for diffuse convergence zones; not measured flow.",
  "wetness_index_wbt", "Convergence-Slope Index", "accumulation_potential",
  "Compound terrain index combining modeled convergence and slope.", "index",
  "external", TRUE, TRUE,
  "Placed with accumulation potential in blueterra; interpreted as a terrain proxy for low-gradient convergence or sediment focusing.",
  "convergence_slope_index", "Convergence-Slope Index", "accumulation_potential",
  "Compound terrain index combining modeled convergence and slope.", "index",
  "external", TRUE, TRUE,
  "Accepted alias for convergence-slope index; interpreted as accumulation potential.",
  "convergence_slope_index_wbt", "Convergence-Slope Index", "accumulation_potential",
  "Compound terrain index combining modeled convergence and slope.", "index",
  "external", TRUE, TRUE,
  "Accepted alias for convergence-slope index; interpreted as accumulation potential.",

  "stream_power_index_wbt", "Terrain Power Index", "transport_potential",
  "Compound terrain index combining modeled contributing area and slope.", "index",
  "external", TRUE, TRUE,
  "Terrain-guided transport potential proxy; not measured current velocity or wave energy.",
  "terrain_power_index", "Terrain Power Index", "transport_potential",
  "Compound terrain index combining modeled contributing area and slope.", "index",
  "external", TRUE, TRUE,
  "Accepted alias for terrain power index; not measured current velocity or wave energy.",
  "sediment_transport_index_wbt", "Sediment Transport Index", "transport_potential",
  "Compound terrain index estimating potential sediment or particulate transport capacity.", "index",
  "external", TRUE, TRUE,
  "Terrain-guided transport potential proxy; not measured sediment flux.",

  "downslope_distance_to_stream_wbt", "Downslope Distance to Pathway", "downslope_pathway_proximity",
  "Modeled downslope distance to an extracted terrain-guided pathway.", "map units",
  "external", TRUE, TRUE,
  "The pathway is treated as a seafloor convergence proxy, not a stream.",
  "downslope_distance_to_pathway", "Downslope Distance to Pathway", "downslope_pathway_proximity",
  "Modeled downslope distance to an extracted terrain-guided pathway.", "map units",
  "external", TRUE, TRUE,
  "Accepted alias for downslope pathway proximity workflows.",
  "elevation_above_stream_wbt", "Elevation Above Pathway", "downslope_pathway_proximity",
  "Vertical separation from the nearest extracted terrain-guided pathway.", "input units",
  "external", TRUE, TRUE,
  "The pathway is treated as a seafloor convergence proxy, not a stream.",
  "elevation_above_pathway", "Elevation Above Pathway", "downslope_pathway_proximity",
  "Vertical separation from the nearest extracted terrain-guided pathway.", "input units",
  "external", TRUE, TRUE,
  "Accepted alias for downslope pathway proximity workflows."
)

save(metric_catalog_data, file = "data/metric_catalog.rda", compress = "xz")
