test_that("polygon, depth-band, point, and cell summaries work", {
  bathy <- example_bathy()
  terrain <- derive_terrain(bathy, metrics = c("slope", "bpi", "roughness"))
  sites <- example_sites()
  zones <- summarize_terrain(terrain, sites)
  expect_true("slope_deg_mean" %in% names(zones))
  zones2 <- summarize_terrain_by_zone(terrain, sites)
  expect_equal(names(zones2), names(zones))
  bands <- summarize_depth_bands(bathy, metrics = terrain, breaks = c(-90, -60, -30, 0))
  expect_s3_class(bands, "tbl_df")
  pts <- suppressWarnings(sf::st_centroid(sites))
  point_values <- extract_terrain_points(terrain, pts)
  expect_true("slope_deg" %in% names(point_values))
  cells <- sample_terrain_cells(terrain, size = 15)
  expect_equal(nrow(cells), 15)
})

test_that("modeling helpers return structured objects", {
  terrain <- derive_terrain(example_bathy(), metrics = c("slope", "bpi", "roughness"))
  cells <- sample_terrain_cells(terrain, size = 40)
  pca <- terrain_pca(cells)
  expect_true(all(c("scores", "loadings", "variance", "model") %in% names(pca)))
  corr <- terrain_correlation(cells)
  expect_s3_class(corr, "tbl_df")
  df <- data.frame(group = rep(c("a", "b"), each = 5), slope = 1:10)
  eff <- terrain_effect_size(df, group = "group", vars = "slope")
  expect_equal(eff$method, "cohens_d")
  mm <- prepare_model_matrix(df, response = "group", vars = "slope")
  expect_equal(nrow(mm$x), nrow(df))
  balanced <- balance_samples(data.frame(group = rep(c("a", "b"), c(2, 5)), v = 1:7), "group")
  expect_equal(as.integer(table(balanced$group))[1], as.integer(table(balanced$group))[2])
})
